### ISSUE TITLE
Json data gets loaded twice?

### ISSUE THREAD

**Issue by CodeByFlo** [konsalex/Airport-Autocomplete-JS#1]
When I use the code in wp it works, but somehow on page load the airports.json gets loaded twice right away and one of them says: An error occurred trying to load the resource (not in the console but in the network tab).

<img width="1280" alt="screenshot 2018-11-07 at 16 07 19" src="https://user-images.githubusercontent.com/44831753/48118826-69ab0980-e2a8-11e8-8799-7953890f5a5c.png">

Do you have any idea what could be the reason?

Also, I think it would be good to store the data not in .rawgit.com because I believe that service will be shut down soon.

**Comment by konsalex** [comment]
Hey @meeuwsen ! Thanks for pointing out that GitRaw is shutting down its servers. When I published my repo the service was running but 💩happens.

Now, this seems strange and I will take a look at it. Do you run the code in Wordpress?

**Comment by meeuwsen** [comment]
Hi @konsalex, 
Yes, I have to run it in Wordpress and when I remove one AirportInput("autocomplete-airport-1"); as a test and keep the other it only loads once.
