### ISSUE TITLE
Airports date set is incomplete. 

### ISSUE THREAD

**Issue by Edmasoud95** [konsalex/Airport-Autocomplete-JS#12]
I noticed that the airports data set is missing some airports, For example DOH which is Qatar's main airport,  I changed the data set manually to fix the issue, I suggest we add a parameter to change the data source.

**Comment by konsalex** [comment]
Hey @Edmasoud95 I will have to admin that the airport list was not updated for a long time (~2years).

I will update and push the new airport list, feel free to check ✌️
